[package]
name = "fxbox_taxonomy"
version = "0.1.1"
authors = ["David Rajchenbach-Teller <dteller@mozilla.com>"]

[dependencies]
serde = "0.6.13"
serde_json = "0.6.0"
serde_macros = "0.6.14"
chrono = "0.2.19"
